INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (1, 'Bruce', 'Wayne', '001000');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (2, 'Steve', 'Rogger', '001001');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (3, 'Robert', 'Starks', '001002');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (4, 'Monalisa', 'Sogan', '001003');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (5, 'Johnny','Walker','001004');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (6, 'Morgan','Stan','001005');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (7, 'Delta','Wave','001006');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (8, 'Stephan','Strange','001007');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (9, 'Nikol','Tesla','001008');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (10, 'Issac','Newton','001009');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (16, 'Tony','Stark','001015');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (11, 'Tom','Moody','001010');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (12, 'Tom','Riddle','001011');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (14, 'Peter','Parker','001013');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMPLOYEE_ID) VALUES (15, 'Jason','Smith','001014');

